version: "3.9"
services:
    rabbitmq:
        container_name: "rabbitmq"
        image: rabbitmq:3-management
        ports:
            - '5672:5672'
            - '15672:15672'
        volumes:
            - 'rabbitmq_data:/var/lib/postgresql/data'
    postgres-db:
        image: postgres:latest
        container_name: "postgres-db"
        ports:
            - '5432:5432'          
        volumes: 
            - postgres-db:/var/lib/postgresql/data            
    paymentgateway-api:
        container_name: "paymentgateway-api"
        image: paymentgateway-api:latest
        build:
            dockerfile: src/external/PaymentGateway.Api/Dockerfile
        ports:
            - '6001:80'
        restart: always
    event-consumers:
        container_name: "event-consumers"
        image: event-consumer:latest
        build:
            dockerfile: src/external/PaymentGateway.Consumers/Dockerfile
        restart: always 
volumes:
  postgres-db:
    driver: local
  rabbitmq_data:        