version: '3.8'
services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - USERNAME=guest
      - PASSWORD=guest
  # postgres-db:
  #   image: postgres:latest
  #   environment:
  #     - USER_ID=postgres
  #     - PASSWORD=postgres
  #     - DATABASE=psotgres
  #   ports:
  #     - '5432:5432'
  #   volumes: 
  #     - postgres-db:/var/lib/postgresql/data
  #     - postgres-logs:/var/lib/postgresql/logs
  paymentgateway-api:
    image: ${DOCKER_REGISTRY-}sidetradecloudapipaymentgateway
    build:
      context: .
      dockerfile: src/external/Sidetrade.Cloud.Api.PaymentGateway.Api/Dockerfile
    depends_on:
      - rabbitmq
  # consumer-events:
  #   image: ${DOCKER_REGISTRY-}sidetradecloudapipaymentgateway
  #   build:
  #     context: .
  #     dockerfile: src/external/Sidetrade.Cloud.Api.PaymentGateway.Consumers/Dockerfile
  #   depends_on:
  #     - rabbitmq
  #     - postgres-db
# volumes:
#   rabbitmq:
#     driver: local 
#   postgres-db:
#     driver: local      

