version: "3.9"
services:
    paymentgateway-api:
        environment:
            - ConnectionStrings__PaymentGatewayContext=server=postgres-db;port=5432;database=postgres;user id=postgres;password=postgres
            - RabbitMqConfig__Host=rabbitmq
            - RabbitMqConfig__Password=guest
            - RabbitMqConfig__Username=guest    
            - RabbitMqConfig__Port=5672
            - RabbitMqConfig__VirtualHost=/
            - RabbitMqConfig__AutomaticRecoveryEnabled=true,
            - RabbitMqConfig__DeliveryMode=RabbitMQDeliveryMode.Durable
            - RabbitMqConfig__RequestedHeartbeat=30
    event-consumers:
        environment:
            - ConnectionStrings__PaymentGatewayContext=server=postgres-db;port=5432;database=postgres;user id=postgres;password=postgres
            - RabbitMqConfig__Host=rabbitmq
            - RabbitMqConfig__Password=guest
            - RabbitMqConfig__Username=guest    
            - RabbitMqConfig__Port=5672
            - RabbitMqConfig__VirtualHost=/
            - RabbitMqConfig__AutomaticRecoveryEnabled=true
            - RabbitMqConfig__DeliveryMode=RabbitMQDeliveryMode.Durable
            - RabbitMqConfig__RequestedHeartbeat=30    
    postgres-db:
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres           